name: maspim
channels:
  - conda-forge
dependencies:
  - python==3.12
  - r-base
  - matplotlib
  - numpy
  - pandas
  - rpy2
  - scipy
  - tqdm
  - scikit-learn
  - scikit-image
  - psutil
  - h5py
  - pillow
  - textdistance
  - astropy
  - pip:
    - opencv-python
    - mfe
